//
//  BSColorUtilsTests.swift
//  BSColorUtilsTests
//
//  Created by bslayter on 2/8/17.
//  Copyright © 2017 bslayter. All rights reserved.
//

import XCTest
import BSColorUtils

class BSColorUtilsTests: XCTestCase {
    
    override func setUp() {
        super.setUp()
        // Put setup code here. This method is called before the invocation of each test method in the class.
    }
    
    override func tearDown() {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
        super.tearDown()
    }
    
    func testExample() {
        let red = UIColor.red
        let color = UIColor.withRGB(red: 255, green: 0, blue: 0)
        
        XCTAssert(red == color, "Red was not equal to color generated by framework")
    }
    
}
