//
//  BSColorUtilsTests.swift
//  BSColorUtilsTests
//
//  Created by bslayter on 2/8/17.
//  Copyright © 2017 bslayter. All rights reserved.
//

import XCTest
import BSColorUtils

class BSColorUtilsTests: XCTestCase {
    
    override func setUp() {
        super.setUp()
        // Put setup code here. This method is called before the invocation of each test method in the class.
    }
    
    override func tearDown() {
        // Put teardown code here. This method is called after the invocation of each test method in the class.
        super.tearDown()
    }
    
    func testRGB() {
        let red = UIColor.red
        let color = UIColor.withRGB(red: 255, green: 0, blue: 0)
        
        XCTAssert(red == color, "Red was not equal to color generated by framework")
        
        let greenish = UIColor.withRGB(red: 0, green: 204, blue: 0)
        let colorObj = UIColor(red: 0, green: 0.8, blue: 0, alpha: 1.0)
        XCTAssert(greenish == colorObj, "Framework color did not equal native color")
    }
    
    func testHex() {
        let red = UIColor.red
        var hexColor = UIColor.withHex(hexString: "#FF0000")
        let smallHex = UIColor.withHex(hexString: "#F00")
        
        XCTAssert(red == hexColor, "Red was not equal to color generated by framework")
        XCTAssert(red == smallHex, "Red was not equal to color generated by framework")
        
        hexColor = UIColor.withHex(hexString: "00cc00")
        var colorObj = UIColor(red: 0, green: 0.8, blue: 0, alpha: 1.0)
        
        XCTAssert(hexColor == colorObj, "Framework color did not equal native color")
        
        hexColor = UIColor.withHex(hexString: "#aF672b")
        colorObj = UIColor.withRGB(red: 175, green: 103, blue: 43)
        
        XCTAssert(hexColor == colorObj, "Framework color did not equal native color")
    }
    
}
